# Generated by Django 4.0.1 on 2022-08-20 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_alt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='alt',
        ),
    ]
